name: JS.ORG Build and Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - run: sudo npm install -g @angular/cli
    - run: npm install && ng build

    name: Deploy to GitHub Pages
    uses: crazy-max/ghaction-github-pages@v3
    with:
      repo: katheesh/katheesh.js
      target_branch: gh-pages
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}